fix(backend): package.json migrate scripts
I see merge conflicts again, so let's merge this independent change
already. I think this is probably due to a package update.

Error fixed is:
```
$ migrate --compiler 'ts:./src/db/compiler.ts' --migrations-dir ./src/db/migrations --store ./src/db/migrate/store.ts
error: unknown option `--compiler'
error Command failed with exit code 1.
```